

        // Extraire le nom du domaine (première ligne)
    NomDomaine = #"Changed Type"{0}[Nom de tache],

    // Supprimer la première ligne
    SansLignedomaine = Table.Skip(#"Changed Type", 1),

    // Ajouter la colonne Domaine en premier
    AddDomaine = Table.AddColumn(SansLignedomaine, "Domaine", each NomDomaine),
    ReorderDomaine = Table.ReorderColumns(AddDomaine, {"Domaine"} & List.RemoveItems(Table.ColumnNames(AddDomaine), {"Domaine"})),

    AddIndex = Table.AddIndexColumn(ReorderDomaine, "Index", 0, 1),
    AddNiveau = Table.AddColumn(AddIndex, "Niveau", each 
        let espaces = Text.Length([Nom de tache]) - Text.Length(Text.TrimStart([Nom de tache]))
        in espaces / 3 + 1
    ),

    rows = Table.ToRecords(AddNiveau),

    BuildHierarchy = List.Accumulate(
        {0..List.Count(rows)-1},
        [compteurs = {0,0,0,0,0,0,0,0,0,0,0,0}, resultats = {}],
        (state, i) =>
            let
                row = rows{i},
                niveau = row[Niveau],
                c = state[compteurs],

                nouveauxCompteurs = List.Generate(
                    () => [n = 0],
                    each [n] < 12,
                    each [n = [n] + 1],
                    each
                        if [n] + 1 = niveau then c{[n]} + 1
                        else if [n] + 1 > niveau then 0
                        else c{[n]}
                ),

                chemin = Text.Combine(
                    List.Transform({0..niveau-1}, each Text.From(nouveauxCompteurs{_})),
                    "."
                ),

                newRow = Record.AddField(Record.AddField(row, "Chemin", chemin), "Profondeur", niveau)
            in
                [compteurs = nouveauxCompteurs, resultats = state[resultats] & {newRow}]
    ),

    FinalTable = Table.FromRecords(BuildHierarchy[resultats]),
    nbRows = List.Count(rows),

    AddCalculs = Table.AddColumn(FinalTable, "tmp", each
        let
            idx = [Index],
            niveau = [Niveau]
        in
        if niveau <> 1 then
            [
                Evenement_charge    = null,
                Evenement_delai     = null,
                Evenement_perimetre = null,
                Impact_cout         = null,
                Impact_delai        = null
            ]
        else
            let
                nextLevel1 = List.First(
                    List.Select(rows, each _[Index] > idx and _[Niveau] = 1),
                    null
                ),
                limitIdx = if nextLevel1 = null then nbRows else nextLevel1[Index],

                children = List.Select(rows, each _[Index] > idx and _[Index] < limitIdx),

                nbCharge    = List.Count(List.Select(children, each _[Type_Evènement] = "charge")),
                nbDelai     = List.Count(List.Select(children, each _[Type_Evènement] = "délai")),
                nbPerimetre = List.Count(List.Select(children, each _[Type_Evènement] = "périmetre")),

                // Conversion text -> number : on extrait la partie numérique avant le "j" ou espace
                ToNumber = (txt as any) =>
                    let
                        str = if txt = null then null else Text.Trim(Text.From(txt)),
                        // Remplacer virgule par point pour les décimaux
                        clean = if str = null then null 
                                else Text.Replace(Text.Replace(str, ",", "."), " ", ""),
                        // Extraire uniquement les chiffres et le point décimal
                        numeric = if clean = null then null
                                  else Text.Select(clean, {"0".."9", "."})
                    in
                        if numeric = null or numeric = "" then null
                        else try Number.From(numeric) otherwise null,

                impactCout = List.Sum(
                    List.Transform(
                        List.Select(children, each _[Type_Evènement] = "charge" or _[Type_Evènement] = "périmetre"),
                        each ToNumber(_[#"Travail réel"])
                    )
                ),

                impactDelai = List.Sum(
                    List.Transform(
                        List.Select(children, each _[Type_Evènement] = "délai"),
                        each ToNumber(_[Durée])
                    )
                )
            in
                [
                    Evenement_charge    = nbCharge,
                    Evenement_delai     = nbDelai,
                    Evenement_perimetre = nbPerimetre,
                    Impact_cout         = impactCout,
                    Impact_delai        = impactDelai
                ]
    ),

    ExpandCols = Table.ExpandRecordColumn(
        AddCalculs, "tmp",
        {"Evenement_charge", "Evenement_delai", "Evenement_perimetre", "Impact_cout", "Impact_delai"}
    ),

    RemoveCols = Table.RemoveColumns(ExpandCols, {"Index", "Niveau"})

in
    RemoveCols